### ISSUE TITLE
Update population_rank to have even larger ranks

### ISSUE THREAD

**Issue by nvkelso** [whosonfirst/whosonfirst-properties#31]
From https://github.com/whosonfirst-data/whosonfirst-data/pull/891/files#r132779994:

The `wof:population_rank` scale is optimized for Tokyo being the largest **locality**. This will work for **region** placetypes fairly well, but may break down for **country** (we could add a couple more ranks to cover that case).

See also:

- https://github.com/whosonfirst/whosonfirst-properties/blob/master/properties/wof.md#population_rank

**Comment by nvkelso** [comment]
Suggest:

rank | population
----- | -----
15 | 20 million
16 | 50 million
17 | 100 million
18 | 1,000 million

**Comment by stepps00** [comment]
Completed in: https://github.com/whosonfirst/whosonfirst-properties/commit/d516e1c72c15152d0d7bcc4f0414299cd6154b17
