### ISSUE TITLE
document ne:*

### ISSUE THREAD

**Issue by missinglink** [whosonfirst/whosonfirst-properties#42]
Heya,

I was looking for the docs for the `ne:*` properties today and I couldn't find them.

Specifically, I was wondering why `ne:iso_a2` could equal `-1`, I'm guessing that means not known or similar, what is the difference between `-1` and `undefined` or `''` for this field?

Thanks

**Comment by nvkelso** [comment]
It means NE doesn't know, or is deliberately inconsistent with ISO.

Please don't build Pelias features on properties other than WOF or MZ.

**Comment by missinglink** [comment]
Unfortunately, it's not possible to avoid using properties from NE and other sources, for placeholder we currently use:

```
    test("^wof:(id|name|placetype|hierarchy|parent_id|country_alpha3|abbreviation|superseded_by|label|population|megacity)$"),
    test("^lbl:(bbox|latitude|longitude)$"),
    test("^geom:(area|bbox|latitude|longitude)$"),
    test("^iso:(country)$"),
    test("^ne:(iso_a2|iso_a3|pop_est)$"),
    test("^edtf:(deprecated)$"),
    test("^mz:(is_current|population)$"),
    test("^gn:(population|pop)$"),
    test("^zs:(pop10)$"),
    test("^qs:(pop|gn_pop)$"),
    test("^wk:(population)$"),
    test("^meso:(pop)$"),
    test("^statoids:(population)$"),
    test("^misc:(photo_sum)$"),
    test("^name:")
```

in particular, the population and abbreviation data is only available from some sources and not available in `wof` or `mz`.

for example, here's an extract from our code:

```javascript
// this function favors mz:population when available, falling back to other properties.
// see: https://github.com/whosonfirst-data/whosonfirst-data/issues/240#issuecomment-294907374
function getPopulation( wof ) {
       if( wof['mz:population'] ){          return wof['mz:population']; }
  else if( wof['wof:population'] ){         return wof['wof:population']; }
  else if( wof['wk:population'] ){          return wof['wk:population']; }
  else if( wof['gn:population'] ){          return wof['gn:population']; }
  else if( wof['gn:pop'] ){                 return wof['gn:pop']; }
  else if( wof['qs:pop'] ){                 return wof['qs:pop']; }
  else if( wof['qs:gn_pop'] ){              return wof['qs:gn_pop']; }
  else if( wof['zs:pop10'] ){               return wof['zs:pop10']; }
  else if( wof['meso:pop'] ){               return wof['meso:pop']; }
  else if( wof['statoids:population'] ){    return wof['statoids:population']; }
  else if( wof['ne:pop_est'] ){             return wof['ne:pop_est']; }
}

// abbreviations and ISO codes
// logic copied from: pelias/whosonfirst src/components/extractFields.js (since modified)
function getAbbreviation( wof ) {
  if( 'country' === wof['wof:placetype'] || 'dependency' === wof['wof:placetype'] ) {
    return wof['wof:country_alpha3'] || wof['ne:iso_a3'];
  } else if( wof['wof:abbreviation'] ) {
    return wof['wof:abbreviation'];
  }
}
```

there are also fields like `edtf:deprecated` and `iso:country` which I don't think can be avoided?

**Comment by missinglink** [comment]
either way, it would be nice to have the data documented so we could make the decisions ourselves.

for what reasons do you suggest we ignore fields not in `mz` or `wof`?

**Comment by nvkelso** [comment]
Can you document here all other sidecar data properties Pelias dips into, please?

Because WOF and MZ are official, normalized, and maintained. There is no contract about the other properties, they are buyer beware.

**Comment by thisisaaronland** [comment]
@missinglink does have a point about `edtf:` which is official and blessed. I will put together a list of "minimal viable namespaces", shortly.

**Comment by missinglink** [comment]
it sounds like the `ne:*` properties are documented in the Natural Earth project and as such don't need to be reproduced here.

we will continue to use the `mz` and `wof` properties as a first priority and only fall back to 'sidecar' properties when we feel it is absolutely necessary.

we're also aware of the 'buyer beware' nature of such fields and will use them at our own risk.
