### ISSUE TITLE
Wikidata vs Wikipedia

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-properties#51]
Right now we use the `wk` prefix, but we source from Wikidata. Untangle the two, catalogue, and update wof-data records.

**Comment by nvkelso** [comment]
I think the wk:wordcount is from the english Wikipedia page? But most
everything else is from Wikidata.

**Comment by thisisaaronland** [comment]
Wikidata uses the "wd:" prefix

**Comment by stepps00** [comment]
Related: https://github.com/whosonfirst-data/whosonfirst-data/issues/1201

**Comment by nvkelso** [comment]
Forward dup of https://github.com/whosonfirst-data/whosonfirst-data/issues/1201, closing.

**Comment by stepps00** [comment]
This issue was meant to track updates in this repo, specifically the json files here: https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/wk

https://github.com/whosonfirst-data/whosonfirst-data/issues/1201 will track updates to the actual WOF records.

**Comment by stepps00** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/pull/1208 merged

**Comment by thisisaaronland** [comment]
See notes here, https://github.com/whosonfirst/whosonfirst-properties/commit/99258a713f7ac6a1198d951f46199c089178f933#commitcomment-29547175

**Comment by nvkelso** [comment]
Responded there...

**Comment by stepps00** [comment]
Looks like this was sorted out -- okay to close?

**Comment by thisisaaronland** [comment]
Yup.
