### ISSUE TITLE
Deprecating WOF Properties

### ISSUE THREAD

**Issue by vicchi** [whosonfirst/whosonfirst-properties#67]
Based on a discussion as part of PR #66 (see https://github.com/whosonfirst/whosonfirst-properties/pull/66#discussion_r186116373 for context), it's unclear what process to follow when the decision is taken to _deprecate_ a WOF property.

The options seem to be ...

1. Add a new property, something along the lines of `"deprecated": "true"` to the JSON property definition file
2. Create a new directory in this repo, perhaps `whosonfirst-properties/deprecated` and `git mv` the JSON property definition file there
3. Delete the JSON property definition file entirely, via `git rm` and let the Git history record this.
4. Something else

Note that there's way to many uses of terms such as _perhaps_ or _something along the lines of_ for my comfort. Which means some discussion and hopefully consensus if needed.

But recording this here so it's not forgotten about.

**Comment by thisisaaronland** [comment]
You should:

1. Add an `edtf:deprecated=YYYYMMDD` property
2. Add a `mz:is_current=0` property

**Comment by nvkelso** [comment]
What Aaron said :)

**Comment by vicchi** [comment]
@thisisaaronland As properties on the root object? Or in a new `properties` object? In other words, should `properties/wof/superseded.json` contain ...

```
{
  "id": 1159080455, 
  "name": "superseded", 
  "prefix": "wof", 
  "description": "", 
  "type": "string",
  "edtf:deprecated": "YYYYMMDD",
  "mz:is_current": 0
}
```

or ...

```
{
  "id": 1159080455, 
  "name": "superseded", 
  "prefix": "wof", 
  "description": "", 
  "type": "string",
  "properties": {
    "edtf:deprecated": "YYYYMMDD",
    "mz:is_current": 0
  }
}
```
... ?

**Comment by thisisaaronland** [comment]
The first.

**Comment by vicchi** [comment]
Closing down this issue as we've now got consensus on and an exemplar of (see #68) deprecating properties.
