### ISSUE TITLE
document mz:hierarchy_label:{placetype} flags

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-properties#69]
See https://github.com/whosonfirst-data/whosonfirst-data/issues/1215

**Comment by nvkelso** [comment]
Noting that @thisisaaronland suggests `mz:hierarchy_label_{placetype}` instead.

**Comment by stepps00** [comment]
added via: https://github.com/whosonfirst/whosonfirst-properties/commit/e0982d8f6cd5ea92da764edadcd40c42d066c214
