### ISSUE TITLE
Create master list of properties

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-properties#70]
Create a single list/lookup table of all properties used in whosonfirst-data records.

**Comment by nvkelso** [comment]
You mean one big readme like we do for sources, instead of just per property prefix like now?

**Comment by stepps00** [comment]
Yep - something that we can refer to, kinda like the sources readme. Probably something I can wire into a make target.

**Comment by stepps00** [comment]
I've added this as part of #99.

I've added a comment (https://github.com/whosonfirst/whosonfirst-properties/pull/99#issue-394851809) about this file going forward.. for now, the json file contains any existing property in any admin record in the 260 per-country admin repos.
