### ISSUE TITLE
deprecate misc properties

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-properties#72]
https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/misc

Deprecate existing `misc:` properties, as they were cleaned up via: https://github.com/whosonfirst-data/whosonfirst-data/pull/979.

Though add a general note that any `misc:` property is possible, per: https://github.com/whosonfirst/py-mapzen-whosonfirst-export/blob/master/mapzen/whosonfirst/export/__init__.py#L370

**Comment by nvkelso** [comment]
Why would those creep back in?

**Comment by stepps00** [comment]
The export code defaults to `misc:` if a record has a property without a `:` separator.

**Comment by nvkelso** [comment]
I think it's fine to keep the export code as is... we just need to document somewhere, like add a README.md to https://github.com/whosonfirst/whosonfirst-properties/tree/master/properties/misc (other dirs there have it, it's missing for misc).
