### ISSUE TITLE
Deprecate wof:label property

### ISSUE THREAD

**Issue by stepps00** [whosonfirst/whosonfirst-properties#84]
Once https://github.com/whosonfirst-data/whosonfirst-data/issues/1540 lands, deprecate the `wof:label` property and update examples/references to the property.

**Comment by thisisaaronland** [comment]
https://github.com/whosonfirst-data/whosonfirst-data/issues/1540#issuecomment-475056154

**Comment by stepps00** [comment]
Deprecating this property is not the correct approach. As mentioned in https://github.com/whosonfirst-data/whosonfirst-data/issues/1540, this property is still useful in cataloguing a "default" label, similar to `wof:name` - it is also being used by various services like Pelias.

We can keep this property, while continuing to curate translated labels in the `label:` properties of a record.

Closing.
