### ISSUE TITLE
Missing Properties from Aliases

### ISSUE THREAD

**Issue by Guilherme-B** [whosonfirst/whosonfirst-properties#98]
I'm using [property_aliases.json](https://github.com/whosonfirst/whosonfirst-properties/blob/master/aliases/property_aliases.json) to ensure I always have the full list of possible source:label combination. However I did notice there are quite a lot missing, especially when it comes to name:language_x_colloquial. Is this file not supposed to keep track of all the possible combinations present in WOF? If not, is there a file which does?

**Comment by missinglink** [comment]
I think this is more a list of synonyms rather than a definitive list of all properties?

**Comment by Guilherme-B** [comment]
Thought so. Any idea if such a definitive list exists?

**Comment by stepps00** [comment]
As @missinglink mentioned, this is a specific list of synonyms we maintain for specific neighbourhood update work. Ultimately, I think this boils down to needing a fix for https://github.com/whosonfirst/whosonfirst-properties/issues/70.

Just to be clear, are you interested in a full list of properties possible in WOF records? I can try to craft something up this week...

**Comment by Guilherme-B** [comment]
@stepps00 - exactly, one which hopefully can be maintained.

**Comment by stepps00** [comment]
Got it.. I'll close this issue out, but track in #70. I've kicked off a simple script to grab all property names, so I'll update that issue once complete.

This has been something I've been meaning to get to, so thanks for the reminder.
